language: csharp
dist: jammy
mono: none

dotnet:
  - 10.0

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev

script:
  - cd "./ThinBasic.NET"
  - dotnet build --configuration Release
  - dotnet test --configuration Release --no-build